# Generated by Django 6.0.6 on 2026-06-09 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Despacho Laboral'", max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('config', models.JSONField(default=dict, help_text='JSON estructura: {"pipelines": [...], "prompts": [{"name", "version", "system_prompt", "variables", "task_type"}], "automations": [{"name", "trigger_event", "actions"}]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
