# Generated by Django 6.0.6 on 2026-06-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=255)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latency_ms', models.IntegerField()),
                ('success', models.BooleanField(default=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.project')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audits', to='tenants.tenant')),
            ],
        ),
    ]
