# Generated by Django 6.0.6 on 2026-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0001_initial'),
        ('tenants', '0002_projecttemplate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contentmaster',
            constraint=models.UniqueConstraint(fields=('tenant', 'project', 'title'), name='unique_master_per_project'),
        ),
    ]
